name: CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for pushing version tags
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Bump version and push tag
      id: bump_version
      run: |
        NEW_TAG=$(npm version patch -m "chore(release): bump to %s")
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
      env:
        GIT_AUTHOR_NAME: GitHub Actions Bot
        GIT_AUTHOR_EMAIL: actions@github.com
        GIT_COMMITTER_NAME: GitHub Actions Bot
        GIT_COMMITTER_EMAIL: actions@github.com

    - name: Push changes to GitHub
      run: |
        git push origin main --follow-tags

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ayushgupta1903/tut:${{ env.NEW_TAG }} .

    - name: Push Docker image
      run: docker push ayushgupta1903/tut:${{ env.NEW_TAG }}
